name: dhammapada
description: "A Dhammapada App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.0
  shared_preferences: ^2.0.15
  dynamic_color: ^1.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/chapters.json
    - assets/verses.json
    - assets/translations/max_muller.json
    - assets/translations/woodwards.json
    - assets/translations/thannisaro.json
    - assets/icon.png

  fonts:
    - family: Castoro
      fonts:
        - asset: assets/fonts/Castoro-Regular.ttf
        - asset: assets/fonts/Castoro-Italic.ttf
          style: italic
