name: Dhammapada
description: "A Dhammapada App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/ic_foreground.png"
  adaptive_icon_background: "assets/ic_background.png"

flutter:
  uses-material-design: true

  assets:
    - assets/chapters.json
    - assets/verses.json
    - assets/icon.png

  fonts:
    - family: Castoro
      fonts:
        - asset: assets/fonts/Castoro-Regular.ttf
        - asset: assets/fonts/Castoro-Italic.ttf
          style: italic
