name: pocket_dhamma
description: "A Dhammapada reader app"
publish_to: 'none'

version: 1.2.1+121

environment:
  sdk: ^3.8.0
  flutter: 3.32.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.0
  shared_preferences: ^2.0.15
  dynamic_color: ^1.7.0
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/chapters.json
    - assets/verses.json
    - assets/translations/max_muller.json
    - assets/translations/woodwards.json
    - assets/translations/thanissaro.json
    - assets/icon.png

  fonts:
    - family: Castoro
      fonts:
        - asset: assets/fonts/Castoro-Regular.ttf
        - asset: assets/fonts/Castoro-Italic.ttf
          style: italic
    - family: Atkinson Hyperlegible
      fonts:
        - asset: assets/fonts/AtkinsonHyperlegible-Regular.ttf
        - asset: assets/fonts/AtkinsonHyperlegible-Bold.ttf
          weight: 700
